name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Env
        run: |
          env | sort | grep GIT
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Install release automaton
        run: |
          echo $GOBIN
          GO111MODULE=on GOBIN=/usr/local/bin go get github.com/appscodelabs/release-automaton@f197c02647e592fcc2bdb0a5d1be18cce6c49be7
      - name: GH_TEST
        # if: startsWith(github.event.ref, 'refs/tags/')
        run: |
          echo "$GITHUB_REF#refs/tags/"
          env | sort | grep GIT
      - name: GH_TEST
        # if: startsWith(github.event.ref, 'refs/tags/')
        run: |
          reponame=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER"/"}
          echo $reponame

