name: IssueComment

on:
  issue_comment:
    types: [created, deleted]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Env
        run: |
          env | sort | grep GIT

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Install release automaton
        run: |
          sudo GO111MODULE=on GOBIN=/usr/local/bin go get github.com/appscodelabs/release-automaton@x7

      - name: Release
        if: ${{ github.event.issue.milestone.title }} != null
        run: |
          release-automaton \
            --release-tracker=${{ github.event.issue.html_url }} \
            --comment-id=${{ github.event.comment.id }} \
            --release=${{ github.event.issue.milestone.title }} \
            --release-file=${{ github.event.issue.milestone.title }}/release.json
