name: Issue

on:
  issues:
    types: [opened, edited, milestoned]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: |
        echo "${{ toJSON(github.event) }}"
